const query = (selector) => document.querySelector(selector);
const queryAll = (selector) => document.querySelectorAll(selector);

export const ui = {
  authenticatedContent: query("#authenticated-content"),
  unauthenticatedContent: query("#unauthenticated-content"),
  userEmailSpan: query("#user-email"),
  logoutBtn: query("#logout-btn"),
  adminOnlyContent: queryAll(".admin-only"),
  loader: query("#loader"),
  filterForm: query("#form"),
  materialSelect: query("#material-select"),
  tipoSelect: query("#tipo-select"),
  espessuraSelect: query("#espessura-select"),
  clearBtn: query("#clear-btn"),
  resultsContainer: query("#results-container"),
  resultsTable: query("#results-table"),
  resultsTableBody: query("#results-table-body"),
  resultsCardsContainer: query("#results-cards-container"),
  emptyState: query("#empty-state"),
  paginationControls: query("#pagination-controls"),
  prevPageBtn: query("#prev-page-btn"),
  nextPageBtn: query("#next-page-btn"),
  pageInfo: query("#page-info"),
  openRegisterModalBtn: query("#open-register-modal-btn"),
  showReservedBtn: query("#show-reserved-btn"),
  registerModal: query("#register-modal"),
  closeRegisterModalBtn: query("#close-register-modal-btn"),
  registerForm: query("#register-form"),
  regMaterialSelect: query("#reg-material"),
  regTipoSelect: query("#reg-tipo"),
  regSubmitBtn: query("#reg-submit-btn"),
  regClearBtn: query("#reg-clear-btn"),
  regNovoMaterialContainer: query("#reg-novo-material-container"),
  regNovoMaterialInput: query("#reg-novo-material-input"),
  regSalvarNovoMaterialBtn: query("#reg-salvar-novo-material-btn"),
  regCancelarNovoMaterialBtn: query("#reg-cancelar-novo-material-btn"),
  regNovoTipoContainer: query("#reg-novo-tipo-container"),
  regNovoTipoInput: query("#reg-novo-tipo-input"),
  regSalvarNovoTipoBtn: query("#reg-salvar-novo-tipo-btn"),
  regCancelarNovoTipoBtn: query("#reg-cancelar-novo-tipo-btn"),
  reserveModal: query("#reserve-modal"),
  closeReserveModalBtn: query("#close-reserve-modal-btn"),
  reserveConfirmBtn: query("#reserve-confirm-btn"),
  reserveInputOs: query("#reserve-input-os"),
  reserveQuantityContainer: query("#reserve-quantity-container"),
  reserveInputQuantidade: query("#reserve-input-quantidade"),
  reserveAvailableText: query("#reserve-available-text"),
  reservedModal: query("#reserved-modal"),
  closeModalBtn: query("#close-modal-btn"),
  reservedModalContent: query("#reserved-modal-content"),
  modalLoader: query("#modal-loader"),
  osSearchInput: query("#os-search-input"),
  createPdfBtn: query("#create-pdf-btn"),
};